import type { NextPage } from 'next'
import Head from 'next/head'
import { ButtonDefault } from '../components/button'
import { Footer, Header } from '../components/navigations'
import Thumbnail from '../assets/images/Video.jpg'
import Image from 'next/future/image'
const Home: NextPage = () => {
  return (
    <div className='relative'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='container mx-auto'>
      <Header/>

      </section>
    </div>
  )
}

export default Home
