import type { NextPage } from 'next'
import Head from 'next/head'
import { ButtonDefault } from '../components/button'
import { Footer, Header } from '../components/navigations'

const Home: NextPage = () => {
  return (
    <div className='relative'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className='container mx-auto text-stone-700 px-40 flex flex-col gap-8 mb-16'>
        <section aria-labelledby='about-us'>
          <h1 className='text-7xl mb-4 text-center font-bold'> Lobe <span className='text-emerald-400'>Tour</span> </h1>
          <p className="text-center text-2xl px-32">Build your first machine learning model in ten minutes. No code or experience required.</p>
        </section>
        <section aria-labelledby='video-tour'>

        </section>
        <section className='call-to-action text-center'>
          <h1 className='text-6xl mb-16 font-bold px-52'>Train yout app with Lobe</h1>
          <ButtonDefault title='download' className='text-white bg-emerald-400 text-xl capitalize'/>
        </section>
      </main>
      <Footer />
    </div>
  )
}

export default Home
